# Generated by Django 6.0.2 on 2026-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_contact_created_at_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
